version: 2
updates:
  - package-ecosystem: npm
    versioning-strategy: increase
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "ypolishchuk-ledger"
      - "pglushchenko-ledger"
